set SynModuleInfo {
  {SRCNAME MPCcore_Pipeline_VITIS_LOOP_42_3 MODELNAME MPCcore_Pipeline_VITIS_LOOP_42_3 RTLNAME MPCcore_MPCcore_Pipeline_VITIS_LOOP_42_3
    SUBMODULES {
      {MODELNAME MPCcore_flow_control_loop_pipe_sequential_init RTLNAME MPCcore_flow_control_loop_pipe_sequential_init BINDTYPE interface TYPE internal_upc_flow_control INSTNAME MPCcore_flow_control_loop_pipe_sequential_init_U}
    }
  }
  {SRCNAME MPCcore_Pipeline_VITIS_LOOP_64_4 MODELNAME MPCcore_Pipeline_VITIS_LOOP_64_4 RTLNAME MPCcore_MPCcore_Pipeline_VITIS_LOOP_64_4
    SUBMODULES {
      {MODELNAME MPCcore_mux_63_16_1_1 RTLNAME MPCcore_mux_63_16_1_1 BINDTYPE op TYPE mux IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME MPCallocate_0627 MODELNAME MPCallocate_0627 RTLNAME MPCcore_MPCallocate_0627
    SUBMODULES {
      {MODELNAME MPCcore_mux_98_8_1_1 RTLNAME MPCcore_mux_98_8_1_1 BINDTYPE op TYPE mux IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME matchFunction_0627 MODELNAME matchFunction_0627 RTLNAME MPCcore_matchFunction_0627
    SUBMODULES {
      {MODELNAME MPCcore_mux_168_32_1_1 RTLNAME MPCcore_mux_168_32_1_1 BINDTYPE op TYPE mux IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
      {MODELNAME MPCcore_mux_168_8_1_1 RTLNAME MPCcore_mux_168_8_1_1 BINDTYPE op TYPE mux IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
      {MODELNAME MPCcore_mux_165_8_1_1 RTLNAME MPCcore_mux_165_8_1_1 BINDTYPE op TYPE mux IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
      {MODELNAME MPCcore_mux_168_16_1_1 RTLNAME MPCcore_mux_168_16_1_1 BINDTYPE op TYPE mux IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME ThreadPE_Pipeline_TFLOOP3 MODELNAME ThreadPE_Pipeline_TFLOOP3 RTLNAME MPCcore_ThreadPE_Pipeline_TFLOOP3
    SUBMODULES {
      {MODELNAME MPCcore_mux_98_32_1_1 RTLNAME MPCcore_mux_98_32_1_1 BINDTYPE op TYPE mux IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME ThreadPE_Pipeline_TFLOOP2 MODELNAME ThreadPE_Pipeline_TFLOOP2 RTLNAME MPCcore_ThreadPE_Pipeline_TFLOOP2}
  {SRCNAME ThreadPE MODELNAME ThreadPE RTLNAME MPCcore_ThreadPE
    SUBMODULES {
      {MODELNAME MPCcore_mux_34_16_1_1 RTLNAME MPCcore_mux_34_16_1_1 BINDTYPE op TYPE mux IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
      {MODELNAME MPCcore_mux_98_16_1_1 RTLNAME MPCcore_mux_98_16_1_1 BINDTYPE op TYPE mux IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
      {MODELNAME MPCcore_mux_94_16_1_1 RTLNAME MPCcore_mux_94_16_1_1 BINDTYPE op TYPE mux IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
      {MODELNAME MPCcore_mul_32s_32s_40_1_1 RTLNAME MPCcore_mul_32s_32s_40_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
      {MODELNAME MPCcore_mux_104_32_1_1 RTLNAME MPCcore_mux_104_32_1_1 BINDTYPE op TYPE mux IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
      {MODELNAME MPCcore_mac_muladd_16s_16s_36s_36_4_1 RTLNAME MPCcore_mac_muladd_16s_16s_36s_36_4_1 BINDTYPE op TYPE all IMPL dsp48 LATENCY 3 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME MPCthread MODELNAME MPCthread RTLNAME MPCcore_MPCthread}
  {SRCNAME MPCcore MODELNAME MPCcore RTLNAME MPCcore IS_TOP 1
    SUBMODULES {
      {MODELNAME MPCcore_mul_16s_5ns_21_1_1 RTLNAME MPCcore_mul_16s_5ns_21_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
      {MODELNAME MPCcore_mux_165_32_1_1 RTLNAME MPCcore_mux_165_32_1_1 BINDTYPE op TYPE mux IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
      {MODELNAME MPCcore_mul_mul_16s_6ns_22_4_1 RTLNAME MPCcore_mul_mul_16s_6ns_22_4_1 BINDTYPE op TYPE all IMPL dsp48 LATENCY 3 ALLOW_PRAGMA 1}
      {MODELNAME MPCcore_mac_muladd_16s_6ns_21s_22_4_1 RTLNAME MPCcore_mac_muladd_16s_6ns_21s_22_4_1 BINDTYPE op TYPE all IMPL dsp48 LATENCY 3 ALLOW_PRAGMA 1}
      {MODELNAME MPCcore_mac_muladd_16s_6s_22ns_22_4_1 RTLNAME MPCcore_mac_muladd_16s_6s_22ns_22_4_1 BINDTYPE op TYPE all IMPL dsp48 LATENCY 3 ALLOW_PRAGMA 1}
      {MODELNAME MPCcore_mul_mul_16s_10ns_22_4_1 RTLNAME MPCcore_mul_mul_16s_10ns_22_4_1 BINDTYPE op TYPE all IMPL dsp48 LATENCY 3 ALLOW_PRAGMA 1}
      {MODELNAME MPCcore_mul_mul_16s_10s_22_4_1 RTLNAME MPCcore_mul_mul_16s_10s_22_4_1 BINDTYPE op TYPE all IMPL dsp48 LATENCY 3 ALLOW_PRAGMA 1}
      {MODELNAME MPCcore_mac_muladd_16s_7ns_22ns_22_4_1 RTLNAME MPCcore_mac_muladd_16s_7ns_22ns_22_4_1 BINDTYPE op TYPE all IMPL dsp48 LATENCY 3 ALLOW_PRAGMA 1}
      {MODELNAME MPCcore_mac_muladd_16s_10ns_22ns_22_4_1 RTLNAME MPCcore_mac_muladd_16s_10ns_22ns_22_4_1 BINDTYPE op TYPE all IMPL dsp48 LATENCY 3 ALLOW_PRAGMA 1}
      {MODELNAME MPCcore_mul_mul_16s_7s_22_4_1 RTLNAME MPCcore_mul_mul_16s_7s_22_4_1 BINDTYPE op TYPE all IMPL dsp48 LATENCY 3 ALLOW_PRAGMA 1}
      {MODELNAME MPCcore_mac_muladd_16s_11s_22ns_22_4_1 RTLNAME MPCcore_mac_muladd_16s_11s_22ns_22_4_1 BINDTYPE op TYPE all IMPL dsp48 LATENCY 3 ALLOW_PRAGMA 1}
      {MODELNAME MPCcore_mac_muladd_16s_8ns_22ns_22_4_1 RTLNAME MPCcore_mac_muladd_16s_8ns_22ns_22_4_1 BINDTYPE op TYPE all IMPL dsp48 LATENCY 3 ALLOW_PRAGMA 1}
      {MODELNAME MPCcore_mac_muladd_16s_8s_22ns_22_4_1 RTLNAME MPCcore_mac_muladd_16s_8s_22ns_22_4_1 BINDTYPE op TYPE all IMPL dsp48 LATENCY 3 ALLOW_PRAGMA 1}
      {MODELNAME MPCcore_mac_muladd_16s_9s_22ns_22_4_1 RTLNAME MPCcore_mac_muladd_16s_9s_22ns_22_4_1 BINDTYPE op TYPE all IMPL dsp48 LATENCY 3 ALLOW_PRAGMA 1}
      {MODELNAME MPCcore_mul_mul_16s_6s_22_4_1 RTLNAME MPCcore_mul_mul_16s_6s_22_4_1 BINDTYPE op TYPE all IMPL dsp48 LATENCY 3 ALLOW_PRAGMA 1}
      {MODELNAME MPCcore_ama_submuladd_16s_9s_6s_22ns_22_4_1 RTLNAME MPCcore_ama_submuladd_16s_9s_6s_22ns_22_4_1 BINDTYPE op TYPE all IMPL dsp48 LATENCY 3 ALLOW_PRAGMA 1}
      {MODELNAME MPCcore_mul_mul_16s_7ns_22_4_1 RTLNAME MPCcore_mul_mul_16s_7ns_22_4_1 BINDTYPE op TYPE all IMPL dsp48 LATENCY 3 ALLOW_PRAGMA 1}
      {MODELNAME MPCcore_mul_mul_16s_11s_22_4_1 RTLNAME MPCcore_mul_mul_16s_11s_22_4_1 BINDTYPE op TYPE all IMPL dsp48 LATENCY 3 ALLOW_PRAGMA 1}
      {MODELNAME MPCcore_GATE_1_0_ROM_AUTO_1R RTLNAME MPCcore_GATE_1_0_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME MPCcore_GATE_1_1_ROM_AUTO_1R RTLNAME MPCcore_GATE_1_1_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME MPCcore_GATE_1_2_ROM_AUTO_1R RTLNAME MPCcore_GATE_1_2_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME MPCcore_GATE_unzip_0_ROM_AUTO_1R RTLNAME MPCcore_GATE_unzip_0_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME MPCcore_GATE_unzip_1_ROM_AUTO_1R RTLNAME MPCcore_GATE_unzip_1_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME MPCcore_GATE_unzip_2_ROM_AUTO_1R RTLNAME MPCcore_GATE_unzip_2_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME MPCcore_GATE_unzip_3_ROM_AUTO_1R RTLNAME MPCcore_GATE_unzip_3_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME MPCcore_GATE_unzip_4_ROM_AUTO_1R RTLNAME MPCcore_GATE_unzip_4_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME MPCcore_GATE_unzip_5_ROM_AUTO_1R RTLNAME MPCcore_GATE_unzip_5_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME MPCcore_Yref_V_RAM_AUTO_1R1W RTLNAME MPCcore_Yref_V_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME MPCcore_Xk_V_RAM_AUTO_1R1W RTLNAME MPCcore_Xk_V_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME MPCcore_UBarUncs_V_RAM_AUTO_1R1W RTLNAME MPCcore_UBarUncs_V_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
}
